### ISSUE TITLE
Please add instruction for customer to request G1 SSL cert and G2 SSL cert is generated by default

### ISSUE THREAD

**Issue by ka7harada** [ibm-cloud-docs/ssl-certificates#2]
Please add  below comment to [Cloud Docs＞SSL Cert>Getting Start>Installing and testing](https://cloud.ibm.com/docs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial#installing-ssl-certs)
to let customer know G2 cert is generated by default for re-issue they need to submit case and ask the re-issue.

Links
```
Link of doc:
https://cloud.ibm.com/docs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial#installing-ssl-certs
GHE: https://github.com/ibm-cloud-docs/ssl-certificates/blob/master/index.md
```

### **Current:**
[Installing and testing](https://cloud.ibm.com/docs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial)

`After the ordering and validating process is complete, you receive an email from the certificate authority that includes your certificate, as well as any necessary intermediate certificates. The method for installation depends on the software you are using. After you complete the installation, to go to http://host.yourdomain.com to confirm the presence of the SSL padlock in the browser address bar that signals an encrypted session. If you get a warning, take any indicated steps to resolve it.cs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial](Installing and testing`

### **Expected:**
Installing and testing

`After the ordering and validating process is complete, you receive an email from the certificate authority that includes your certificate, as well as any necessary intermediate certificates. The method for installation depends on the software you are using. After you complete the installation, to go to http://host.yourdomain.com to confirm the presence of the SSL padlock in the browser address bar that signals an encrypted session. If you get a warning, take any indicated steps to resolve it.cs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial](Installing and testing
`
**Note:
If customer need G1 root certificate, please raise case for asking certificate’s  re-issue. When you order SSL certification from portal G2 Is automatically issued.**

**Comment by gudrun-wolfgram** [comment]
Hello Kanako - Thank you for submitting this item for update. I have drafted the following note in the staging location of the Before you begin section of Ordering SSL certificates topic. If this is correct, I will publish the change to production. Thank you for reviewing. 

**SSL certificates getting started > Before you begin**
https://test.cloud.ibm.com/docs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial#byb-getting-started-tutorial

**Important:** If you are ordering a Microsoft certificate, by default the Federal Common Policy CA G2 root certificate is issued. If you need a Federal Common Policy CA G1 root certificate, you must create a support case. For more information, see [Using the Support Center](https://test.cloud.ibm.com/docs/get-support?topic=get-support-using-avatar).

**Comment by ka7harada** [comment]
Thank you. Basically I'm ok with your draft.
 
1)Link
https://test.cloud.ibm.com/docs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial#byb-getting-started-tutorial. I could not open it.
-> I could not open it
If you are saying you will add below comment in Cloud Docs＞SSL Cert>Getting Start page then I’m ok with it

2) https://test.cloud.ibm.com/docs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial#byb-getting-started-tutorial. I could not open it.
If you are saying you will add below comment in Cloud Docs＞SSL Cert>Getting Start page then I’m ok with it

2)Draft
I’m ok with below comment and included link.

`Important: If you are ordering a Microsoft certificate, by default the Federal Common Policy CA G2 root certificate is issued. If you need a Federal Common Policy CA G1 root certificate, you must create a support case. For more information, see Using the Support Center.`

**Comment by gudrun-wolfgram** [comment]
The new note is available in the _Before you begin_ section, here: 

**Getting started tutorial for SSL certificates**
https://cloud.ibm.com/docs/ssl-certificates?topic=ssl-certificates-getting-started-tutorial#installing-ssl-certs

**Comment by gudrun-wolfgram** [comment]
Closing this issue.
